task: erqa
dataset_path: /data/klx/hf_dataset/ERQA/
load_from_disk: true
eval_split: test
doc_to_visual: !function process.erqa_doc_to_visual
doc_to_text: !function process.erqa_doc_to_text
doc_to_target: "answer"
output_type: generate_until
generation_kwargs:
  max_new_tokens: 128
  temperature: 0
  do_sample: false
  top_p: 1.0
  num_beams: 1
# metrics
process_results: !function process.erqa_process_results
metric_kwargs:
  metric: erqa_score
  aggregation: !function process.erqa_aggregate_results
  higher_is_better: true