task: where2place-bbox
dataset_path: /data/klx/hf_dataset/where2place/
dataset_kwargs:
  pre_prompt: You are an agent who reasons about free space and spatial relations.
  post_prompt: Your answer should be a tuple (min_x, max_x, min_y, max_y) indicating the bounding box of the target region. min_x, max_x, min_y, max_y are normalized image coordinates between 0 and 1.
load_from_disk: true
eval_split: test
doc_to_visual: !function process.where2place_doc_to_visual
doc_to_text: !function process.where2place_doc_to_text
doc_to_target: "id"
output_type: generate_until
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: false
  top_p: 1.0
  num_beams: 1
# metrics
process_results: !function process.where2place_process_results
metric_kwargs:
  metric: reference_acc
  aggregation: !function process.where2place_aggregate_results
  higher_is_better: true