task: where2place
dataset_path: /8T/klx/klx/hf_dataset/where2place/point_questions.jsonl
dataset_kwargs:
  image_dir: /8T/klx/klx/hf_dataset/where2place/images/
  target_image_dir: /8T/klx/klx/hf_dataset/where2place/masks/
load_from_disk: true
doc_to_visual: !function process.where2place_doc_to_visual
doc_to_text: !function process.where2place_doc_to_text
doc_to_target: "id"
output_type: generate_until
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# metrics
process_results: !function process.where2place_process_results
metric_kwargs:
  metric: reference_acc
  aggregation: mean
  higher_is_better: true